### ISSUE TITLE
Document Uploading

### ISSUE THREAD

**Issue by oyewunmio** [thoth2357/STAT-ARCHIVE#2]
The users shouldn't be able to upload Non-Pdf Documents which won't produce thumbnails. 
![Screenshot_20230805_132348](https://github.com/thoth2357/STAT-ARCHIVE/assets/42620838/576dfd18-35c6-4d80-9bc4-627fcd5454c7)

**Comment by thoth2357** [comment]
Ok Server side Validation has been added in new commits to Validate content type of Documents before been uploaded,picture below shows picture of error notification when a non pdf document is uploaded
![Screenshot_20230805_134449](https://github.com/thoth2357/STAT-ARCHIVE/assets/98170427/0b8b831a-0049-401e-b0bd-95474d1df196)
